name: generate snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RD0503
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push a la rama output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git rm -rf . > /dev/null 2>&1 || true
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "generate snake"
          git push --force origin output
